version: '3.8' 

services:
  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    volumes:
      - ./data/db:/var/lib/postgresql/data  
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
    ports:
      - "5432:5432"  
